name: Trigger auto deployment for bookstorecoainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/bookstorecoainer-AutoDeployTrigger-8714b400-5531-4560-8bdb-1f52fa595e57.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BOOKSTORECOAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOOKSTORECOAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOOKSTORECOAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bookstore20250113211035.azurecr.io
          registryUsername: ${{ secrets.BOOKSTORECOAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOOKSTORECOAINER_REGISTRY_PASSWORD }}
          containerAppName: bookstorecoainer
          resourceGroup: BookStoreBackend_group
          imageToBuild: bookstore20250113211035.azurecr.io/bookstorecoainer:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


